/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Excepciones.PatronIncorrecto;
import Excepciones.PatronEmailIncorrecto;
import Excepciones.DatoObligatorio;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import tema8practica3ejercicio2.Tema8Practica3Ejercicio2;

/**
 *
 * @author 1gdaw07
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.getContentPane().setBackground(Color.green);
        //getContentPane().setBackground(Color.yellow); lo mismo pero poniendo el color en propiedades
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precioCategoria = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rFam = new javax.swing.JRadioButton();
        rInd = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfNomSoc = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panHijos = new javax.swing.JPanel();
        panHijo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfNomHijo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comDia = new javax.swing.JComboBox<>();
        comMes = new javax.swing.JComboBox<>();
        comAño = new javax.swing.JComboBox<>();
        bX = new javax.swing.JButton();
        bAñadir = new javax.swing.JButton();
        bInscribirse = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tformTel = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Si, deseo/deseamos hacerme/hacernos socio/s del Zoo-Club. Cuota de ingreso 15€");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Categoría:");

        precioCategoria.add(rFam);
        rFam.setForeground(new java.awt.Color(255, 0, 153));
        rFam.setText("Familiar: 68€");
        rFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rFamActionPerformed(evt);
            }
        });

        precioCategoria.add(rInd);
        rInd.setForeground(new java.awt.Color(255, 0, 153));
        rInd.setText("Individual: 32€");
        rInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rIndActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("Nombre:");

        jLabel5.setForeground(new java.awt.Color(255, 0, 153));
        jLabel5.setText("Apellidos:");

        jLabel6.setForeground(new java.awt.Color(255, 0, 153));
        jLabel6.setText("Teléfono:");

        jLabel7.setForeground(new java.awt.Color(255, 0, 153));
        jLabel7.setText("Correo Electrónico");

        tfNomSoc.setEnabled(false);
        tfNomSoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomSocActionPerformed(evt);
            }
        });

        tfApellido.setEnabled(false);
        tfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoActionPerformed(evt);
            }
        });

        tfCorreo.setEnabled(false);
        tfCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCorreoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Hijos: (sólo menores de edad y en categoria familiar)");

        panHijos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 0), 1, true));
        panHijos.setEnabled(false);

        panHijo.setEnabled(false);

        jLabel9.setText("Nombre:");

        tfNomHijo.setEnabled(false);
        tfNomHijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomHijoActionPerformed(evt);
            }
        });

        jLabel10.setText("Fecha de Nac.:");

        comDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comDia.setSelectedIndex(-1);
        comDia.setEnabled(false);

        comMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        comMes.setSelectedIndex(-1);
        comMes.setEnabled(false);

        comAño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000" }));
        comAño.setSelectedIndex(-1);
        comAño.setEnabled(false);

        bX.setBackground(new java.awt.Color(153, 255, 153));
        bX.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bX.setForeground(new java.awt.Color(255, 0, 0));
        bX.setText("X");
        bX.setEnabled(false);

        javax.swing.GroupLayout panHijoLayout = new javax.swing.GroupLayout(panHijo);
        panHijo.setLayout(panHijoLayout);
        panHijoLayout.setHorizontalGroup(
            panHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHijoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNomHijo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panHijoLayout.setVerticalGroup(
            panHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHijoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHijoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(tfNomHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(comDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panHijosLayout = new javax.swing.GroupLayout(panHijos);
        panHijos.setLayout(panHijosLayout);
        panHijosLayout.setHorizontalGroup(
            panHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHijosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panHijosLayout.setVerticalGroup(
            panHijosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHijosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panHijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        bAñadir.setForeground(new java.awt.Color(0, 102, 0));
        bAñadir.setText("Añadir Hijo");
        bAñadir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bAñadir.setEnabled(false);

        bInscribirse.setBackground(new java.awt.Color(102, 255, 102));
        bInscribirse.setForeground(new java.awt.Color(51, 102, 255));
        bInscribirse.setText("Inscribirse");
        bInscribirse.setEnabled(false);
        bInscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bInscribirseActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 0));
        jLabel11.setText("Atención! Esta es una hoja de inscripcion de ejemplo, si desea realmente Inscribirse");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 0));
        jLabel12.setText("al Zoo-Club de Barcelona, pinche en el siguiente enlace");

        try {
            tformTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tformTel.setEnabled(false);
        tformTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tformTelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bAñadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(bInscribirse)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panHijos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rFam)
                                                .addGap(18, 18, 18)
                                                .addComponent(rInd))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(tformTel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                                .addComponent(tfCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfApellido, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfNomSoc, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rFam)
                    .addComponent(rInd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfNomSoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tformTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panHijos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAñadir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bInscribirse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hoja de Inscripción");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(347, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rIndActionPerformed
    habilitar();     
    }//GEN-LAST:event_rIndActionPerformed

    private void rFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rFamActionPerformed
    habilitar();
    habilitarFam();
    
    }//GEN-LAST:event_rFamActionPerformed

    private void tfNomSocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomSocActionPerformed
try
    {
        if(tfNomSoc.getText().isEmpty())
        {
            throw new DatoObligatorio();
        }
        Pattern patron =Pattern.compile("[^0-9]*");
        Matcher encaja=patron.matcher(tfNomSoc.getText());
        if(!encaja.matches())
        {
            throw new PatronIncorrecto();
        }
        tfApellido.requestFocus();
    }
    catch(PatronIncorrecto e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Patron Incorrecto");
        tfNomSoc.requestFocus();
    }
    catch(DatoObligatorio e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Dato obligatorio");
        tfNomSoc.requestFocus();
    }
    catch(Exception e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Problema de tipo: "+e.getMessage());
        tfNomSoc.requestFocus();
    }
    }//GEN-LAST:event_tfNomSocActionPerformed

    private void tfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoActionPerformed
try
    {
        if(tfApellido.getText().isEmpty())
        {
            throw new DatoObligatorio();
        }
        Pattern patron =Pattern.compile("[^0-9]*");
        Matcher encaja=patron.matcher(tfApellido.getText());
        if(!encaja.matches())
        {
            throw new PatronIncorrecto();
        }
        tformTel.requestFocus();
    }
    catch(PatronIncorrecto e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Patron Incorrecto");
        tfApellido.requestFocus();
    }
    catch(DatoObligatorio e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Dato obligatorio");
        tfApellido.requestFocus();
    }
    catch(Exception e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Problema de tipo: "+e.getMessage());
        tfApellido.requestFocus();
    }
    }//GEN-LAST:event_tfApellidoActionPerformed

    private void tfCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCorreoActionPerformed
try
    {
        if(tfCorreo.getText().isEmpty())
        {
            throw new DatoObligatorio();
        }
        Pattern patronEmail = Pattern.compile("^(.+)@(.+)$");
        Matcher encaja=patronEmail.matcher(tfCorreo.getText());
        if(!encaja.matches())
        {
            throw new PatronEmailIncorrecto();
        }
        bInscribirse.setEnabled(true);
    }
    catch (PatronEmailIncorrecto e)
    {
        javax.swing.JOptionPane.showMessageDialog(this,"Patron de Email incorrecto");
        tfCorreo.requestFocus();
    }
    catch(DatoObligatorio e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Dato obligatorio");
        tfCorreo.requestFocus();
    }
    catch(Exception e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Problema de tipo: "+e.getMessage());
        tfCorreo.requestFocus();
    }
    }//GEN-LAST:event_tfCorreoActionPerformed

    private void tformTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tformTelActionPerformed
    tfCorreo.requestFocus();
    }//GEN-LAST:event_tformTelActionPerformed

    private void bInscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bInscribirseActionPerformed
       if(rInd.isSelected())
       {
        Tema8Practica3Ejercicio2.añadirSocioIndividual(tfNomSoc.getText(), tfApellido.getText(),tformTel.getText(),tfCorreo.getText());
        JOptionPane.showMessageDialog(this,"te has inscrito con exito");
       }
       if(rFam.isSelected())
       {
        Tema8Practica3Ejercicio2.añadirSocioFamiliar(tfNomSoc.getText(), tfApellido.getText(),tformTel.getText(),tfCorreo.getText(),tfNomHijo.getText(),comDia.getSelectedItem(),comMes.getSelectedItem(),comAño.getSelectedItem());
        JOptionPane.showMessageDialog(this,"tu familia se ha inscrito con exito");
       }
       System.exit(0);
    }//GEN-LAST:event_bInscribirseActionPerformed

    private void tfNomHijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomHijoActionPerformed
try
    {
        if(tfNomHijo.getText().isEmpty())
        {
            throw new DatoObligatorio();
        }
        Pattern patron =Pattern.compile("[^0-9]*");
        Matcher encaja=patron.matcher(tfNomHijo.getText());
        if(!encaja.matches())
        {
            throw new PatronIncorrecto();
        }
        comDia.requestFocus();
    }
    catch(PatronIncorrecto e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Patron Incorrecto");
        tfNomHijo.requestFocus();
    }
    catch(DatoObligatorio e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Dato obligatorio");
        tfNomHijo.requestFocus();
    }
    catch(Exception e)
    {
        javax.swing.JOptionPane.showMessageDialog(this, "Problema de tipo: "+e.getMessage());
        tfNomHijo.requestFocus();
    }
    }//GEN-LAST:event_tfNomHijoActionPerformed
    public void habilitar()
    {
        tfNomSoc.setEnabled(true);
        tfApellido.setEnabled(true);
        tformTel.setEnabled(true);
        tfCorreo.setEnabled(true);
        rFam.setEnabled(false);
        rInd.setEnabled(false);
    }
    public void habilitarFam()
    {
        tfNomHijo.setEnabled(true);
        bAñadir.setEnabled(true);        
        comDia.setEnabled(true);
        comMes.setEnabled(true);
        comAño.setEnabled(true);
        panHijos.setEnabled(true);
        panHijo.setEnabled(true);
        bX.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bInscribirse;
    private javax.swing.JButton bX;
    private javax.swing.JComboBox<String> comAño;
    private javax.swing.JComboBox<String> comDia;
    private javax.swing.JComboBox<String> comMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panHijo;
    private javax.swing.JPanel panHijos;
    private javax.swing.ButtonGroup precioCategoria;
    private javax.swing.JRadioButton rFam;
    private javax.swing.JRadioButton rInd;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfNomHijo;
    private javax.swing.JTextField tfNomSoc;
    private javax.swing.JFormattedTextField tformTel;
    // End of variables declaration//GEN-END:variables
}
